server:
  port: 8080

spring:
  datasource:
    # MySql
    url: jdbc:mysql://60.204.226.31:33060/my_study_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: keep1233keep1233
